### ISSUE TITLE
output warnings directly after running auto.sh

### ISSUE THREAD

**Issue by limxtop1989** [txthinking/google-hosts#100]
**Question 1**
output warnings directly:
limxtop@IdeaPad:~/bin/google-hosts/scripts$ ./auto.sh 
[WARNING] *.google.com
[WARNING] accounts.google.com
[WARNING] checkout.google.com
[WARNING] adwords.google.com
[WARNING] mail.google.com
[WARNING] *.mail.google.com
[WARNING] *.googleusercontent.com
[WARNING] *.gstatic.com
[WARNING] *.googleapis.com
[WARNING] *.appspot.com
[WARNING] *.googlecode.com
[WARNING] *.google-analytics.com
[WARNING] ssl.google-analytics.com

This is the content of /etc/resolv.conf file:
nameserver 127.0.0.1
search DHCP HOST

**Question 2:**
How to make sure that I use google DNS or open DNS? I made the content of /etc/resolv.conf file to be
nameserver 8.8.8.8
nameserver 8.8.4.4
search DHCP HOST

and run auto.sh for a couple of hours, finally copy generated hosts file to cover the hosts file in /etc. but I can't access https:www.google.com still. where is the problem?

**suggestion**
why not create a FQA file or describe more clearly how to use it?

**Comment by txthinking** [comment]
On Wed, Nov 9, 2016 at 10:23 PM limxtop1989 <notifications@github.com>
wrote:

> *Question 1*
> output warnings directly:
> limxtop@IdeaPad:~/bin/google-hosts/scripts$ ./auto.sh
> [WARNING] *.google.com
> [WARNING] accounts.google.com
> [WARNING] checkout.google.com
> [WARNING] adwords.google.com
> [WARNING] mail.google.com
> [WARNING] *.mail.google.com
> [WARNING] *.googleusercontent.com
> [WARNING] *.gstatic.com
> [WARNING] *.googleapis.com
> [WARNING] *.appspot.com
> [WARNING] *.googlecode.com
> [WARNING] *.google-analytics.com
> [WARNING] ssl.google-analytics.com
>
> This is the content of /etc/resolv.conf file:
> nameserver 127.0.0.1
> search DHCP HOST
>
This auto.sh script find IP from this IP POOL: $ nslookup -q=TXT _
netblocks.google.com 8.8.4.4. IP may be all dead.
Then:
You need find IP from OTHER POOL and don't make it public.
or use other proxy.

> *Question 2:*
> How to make sure that I use google DNS or open DNS? I made the content of
> /etc/resolv.conf file to be
>
$ nslookup [ENTER]

**Comment by txthinking** [comment]
Please read this https://peering.google.com/#/learn-more/faq for why you need different DNS.

**Comment by go2run** [comment]
if I could gethttps://peering.google.com/#/learn-more/faq
why do I need hosts...
