### ISSUE TITLE
如何在一定的范围内寻找

### ISSUE THREAD

**Issue by dyis** [txthinking/google-hosts#21]
64.18.0.0/20
http://www.adminsub.net/ipv4-subnet-calculator/64.18.0.0/20
216.239.32.0/19
http://www.adminsubnet.net/ipv4-subnet-calculator/216.239.32.0/19

似乎没这个功能，能否添加

**Comment by zhjawe** [comment]
我也有这个问题，似乎auto.sh跑出来的结果不能用。

**Comment by sosp** [comment]
需要自己选定Ip段的吧

2015-01-07 17:49 GMT+08:00 zhjawe <notifications@github.com>:

**Comment by zhjawe** [comment]
./auto.sh 64.18 64.233.160 66.102 66.249.80 72.14.192 74.125 173.194 207.126.144 209.85.128 216.58.208 216.239.32 这是我解析出来的IP段，find.sh以后用filter过滤，一个都没有。

**Comment by zhjawe** [comment]
在教育网内运行也是这个结果，教育网可以直连google

**Comment by zhjawe** [comment]
找到问题了，没装nmap

**Comment by txthinking** [comment]
许久的issue，今晚才开始弄，提交到develop分支了 :octopus:

**Comment by txthinking** [comment]
合并进了master, 查询更快了. 我的1cpu, 2m带宽 5个小时跑完. 
如果你的机器好，可以自行修改`scripts/find.sh`调节 `max_process`值 (小心太大机器卡死)

**Comment by txthinking** [comment]
**注意**
find.sh和getssl.sh 接受的参数变了, 如果单独使用这两个脚本时建议看个README
