### ISSUE TITLE
google hosts 是不是不可以用了

### ISSUE THREAD

**Issue by hesen2006cn** [txthinking/google-hosts#29]
curl -s http://tx.txthinking.com/fuckGFW.py | sudo python 后还是不行。

全国网民就靠你这个伟大的程序来获取新知识了，拜托了

**Comment by zhaodaniu** [comment]
是啊，又被封了。。。大神，请问Google搜索对应的host是哪一个啊？

**Comment by alvis-huang** [comment]
你把那个hosts里的内容都拷贝到你电脑的hosts文件里就好了

 

发件人: bounces+848413-930e-yilence=163.com@sgmail.github.com [mailto:bounces+848413-930e-yilence=163.com@sgmail.github.com] 代表 xiaoyao
发送时间: 2015年1月1日 23:58
收件人: txthinking/google-hosts
主题: Re: [google-hosts] google hosts 是不是不可以用了 (#29)

 

是啊，又被封了。。。大神，请问Google搜索对应的host是哪一个啊？

**Comment by leafcoder** [comment]
这么搞，估计用不了多久，Google的IP段慢慢的都得被封了

**Comment by txthinking** [comment]
updated 我尽量每天上班前更新一次

**Comment by txthinking** [comment]
已经搞好机器， 每天2点自动更新

**Comment by inix** [comment]
辛苦了

**Comment by yxuechao007** [comment]
感谢你们的辛苦工作

2015-02-10 16:29 GMT+08:00 Cloud <notifications@github.com>:

**Comment by ShujiaHuang** [comment]
赞一个！！

**Comment by txthinking** [comment]
updated

**Comment by joingithubcom** [comment]
新手，路由dnsmasq配置好了，访问不了google，研究发现手机用ip直接访问能进google首页。手机ping出的ip是对的，虽然是ping超时。难道dnsmasq会自动在ping不通的时候转上级dns服务器，有高手能解答我的困惑吗

**Comment by txthinking** [comment]
$ dig google.com @YOUR_DNS_SERVER_IP

看看得出来的结果是不是和你conf文件里配置的一样

**Comment by joingithubcom** [comment]
没有条件做以上查看。但我试过添加一条将baidu指向google的ip也不能访问。
另外，本该是一个域名对应多个ip，而实际上看配置文件是多个域名对应一个ip。不知是怎么样的查询转换，也许是受墙影响。
