### ISSUE TITLE
关于youtube的支持

### ISSUE THREAD

**Issue by qwwujh** [txthinking/google-hosts#37]
能更新googlevideo的域名和IP吗

**Comment by txthinking** [comment]
每天3点更新android和youtube相关IP, 不能保证绝对可用

**Comment by audiebantzhan** [comment]
好的。多谢

**Comment by joingithubcom** [comment]
奇怪的问题，电脑手机都不做修改，通过路由翻，都能浏览u2b，只有手机能播放。

**Comment by rexdf** [comment]
u2b有异常多的 r8---sn-5hn7su7e.googlevideo.com 这种样子的域名，每次都不同，而且我的情况是每次都不在列表里面。
有没有什么办法记录或者扫描出它的这种域名

**Comment by joingithubcom** [comment]
@rexdf，dnsmasq没这个问题*.googlevideo.com对它来说都一样。tx可以在现有精简的基础继续精简conf文件。

**Comment by rexdf** [comment]
@joingithubcom 我是windows上面的，而且路由器不太好部署。hosts文件是不支持dnsmask的。

windows下面有没有可以自己配置的轻量级dns服务器啊

**Comment by rexdf** [comment]
@joingithubcom  我测试了下 如果用dnsmasq在路由器上面则依然无法播放  谷歌返回的是404 这种域名是有特定不同ip的。google.dnsmasq.conf里面根本没有这个规则匹配*.googlevideo.com。

**Comment by joingithubcom** [comment]
我路由器dnsmasq对google指定了某小众翻墙dns。我电脑不能播放，但手机可以播放。只能网页看，安卓客户端更新不了google服务用不了，不知ios有无客户端

**Comment by joingithubcom** [comment]
你说没有这个匹配规则是因为tx没彻底完成精简。比如m.youtube.com和www.youtube.com都是同一个ip，可精简为youtube.com，这样访问类似xyz.youtube.com也不会出错。

**Comment by rexdf** [comment]
我是自己跑出来的，而且我补充了jp,tw,hk,sg等，跑了12多个小时呢。
googlevideo应该是有问题的 
对它的访问 要么是https的，要么是SPDY3的 但是返回的要么是404要么是链接重置。 我现在有点怀疑是gfw的某种干扰影响了视频传输。
没挂vpn的情况下，我对*.googlevideo.com手动换了很多ip，其中均是ping没有问题，部分curl是reset by peer，还有部分就是被hold住而返回(这种的就是chrome里面返回404的ip)。

**Comment by txthinking** [comment]
Youtube 的域名在scripts/hosts.do, 可能并不全或者有个别过期了.
scripts/hosts.do的域名是单独用scripts/getip.sh跑的, 看看脚本上面注释.
自动脚本暂时没有跑这个.
*.youtube.com 这个只是web页面, youtube视频内容域名的规则, 需要研究, 有知情人士还忘告知.

2015-03-15 15:32 GMT+08:00 rexdf <notifications@github.com>:

> 我是自己跑出来的，而且我补充了jp,tw,hk,sg等，跑了12多个小时呢。
> googlevideo应该是有问题的
> 对它的访问 要么是https的，要么是SPDY3的 但是返回的要么是404要么是链接重置。 我现在有点怀疑是gfw的某种干扰影响了视频传输。
> 没挂vpn的情况下，我对*.googlevideo.com手动换了很多ip，其中均是ping没有问题，部分curl是reset by
> peer，还有部分就是被hold住而返回(这种的就是chrome里面返回404的ip)。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/37#issuecomment-80892412>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by qwwujh** [comment]
目前YouTube建议用hosts直连www.YouTube.com,然后会有部分的视频资源会被解析到北京的服务器上

**Comment by qwwujh** [comment]
另外gdgny.org上有个gdgDNS项目,将其中*.Googlevideo.com 的hosts指向其解析的IP即可

**Comment by qwwujh** [comment]
另@rexdf ping得通只是代表了没有被路由封锁,并不代表没被封80,443端口

**Comment by guaitai** [comment]
广东电信 的  210.61.148.34  r（X）---sn-（xxxxx） .googlevideo.com，可以直接播放youtube，已经用了好几个月了

**Comment by audiebantzhan** [comment]
非常感谢！

**Comment by chenglu** [comment]
// 另外gdgny.org上有个gdgDNS项目,将其中*.Googlevideo.com 的hosts指向其解析的IP即可

@qwwujh 请不要建议这么做，谢谢。我们的 DNS 仅限谷歌技术开发者研究技术用，反代服务器 IP 以及 DNS 服务器 IP 都请不要泄露。130.211.251.200 这都是我们用过的 IP 地址。

// IP地址 ：210.61.148.34

@guaitai 这个是 GDGDNS 用过的台湾中华电信的 IP 地址，因为流量费用过高，停掉了。也请您珍惜网络资源，不要将这些服务器地址分享出去，谢谢。

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,还可以看很多海外禁网新闻，速度不错
