### ISSUE TITLE
您好，我想试着将其移植到android下使用，有些问题还望解答

### ISSUE THREAD

**Issue by onewilk** [txthinking/google-hosts#46]
我看了readme,需要如下依赖
#### 脚本依赖

* grep (GNU grep) 2.20
* sed (GNU sed) 4.2.2
* awk (GNU awk) 4.1.1
* nmap v6.46
* dig v9.9.2-P2
* curl (OpenSSL/1.0.1j) 7.37.0

原谅我Linux水平太差，shell只能看懂其中一点。。。
据我所知以上的大多依赖需要busybox的支持，现有脚本直接放到手机里面跑不起来。。。
想问下您有移植到android上的打算么，或者能帮我理解下实现么。。。

**Comment by LGA1150** [comment]
@onewilk
找不到for android版本的话，可自行用源码编译
我昨天就在手机上用c4droid编译了个tcping

**Comment by txthinking** [comment]
目前即使通过其他语言重写部分功能, android 上第一次运行会很占资源
