### ISSUE TITLE
Automatic/nightly update of the hosts script

### ISSUE THREAD

**Issue by TimothyGu** [txthinking/google-hosts#53]
Hi, thank you for this great project. It helps my mom in China who is visiting Google daily a whole lot. However, instead of updating this manually on a sporadic interval, it might be more feasible to update the hosts script through an automatic means, e.g. with a cron job. It shouldn't be too hard to set this up on a cloud server/VPS or a regular PC. Sorry about this English post BTW as I don't have pinyin IME installed.

**Comment by HankAviator** [comment]
想法不错，分摊风险下来应该能大大减缓被封的速度。对了，作者怎么没放捐助方式？如果租VPS，像我这样的技术盲还可以为项目做点什么……

**Comment by txthinking** [comment]
有空我找个机器弄个cron自动更新

2015-01-03 19:10 GMT+08:00 Hank Quakevauld <notifications@github.com>:

> 想法不错，分摊风险下来应该能大大减缓被封的速度。对了，作者怎么没放捐助方式？如果租VPS，像我这样的技术盲还可以为项目做点什么……
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/53#issuecomment-68591350>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by HankAviator** [comment]
安卓上 最新一批刚刚挂掉

**Comment by HankAviator** [comment]
暂时转战全v6环境了，会持续关注v4项目。
另外，不知何故，v6 hosts注释掉了谷歌同步服务器android.clients.google.com。如果该服务器不能连接上，那么所有软件（inbox, keep，但翻译不受限制）都会等待同步完成才会继续运行，即使它们本身连接的地址是与同步地址不同。等有时间详细写写。

**Comment by txthinking** [comment]
已经搞好机器， 每天2点自动更新

**Comment by TimothyGu** [comment]
@txthinking 谢谢！

**Comment by hydRAnger** [comment]
@txthinking 谢谢
