### ISSUE TITLE
请问如何看youtube的视频？

### ISSUE THREAD

**Issue by wy353208214** [txthinking/google-hosts#55]
貌似修改hosts的工具都没法看，想请教下我该如何做呢？

**Comment by txthinking** [comment]
楼上所言极是

**Comment by wizholy** [comment]
只能挂VPN吗？

**Comment by BJHZ** [comment]
是的目前只有这个放法，且绝大多数VPN看youtube效果不佳。目前还没有发现效果出众的。

在 2015-02-12 19:06:54，"wizholy" <notifications@github.com> 写道：


只能挂VPN吗？

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,速度不错
