### ISSUE TITLE
更换可用谷歌IP的一点建议

### ISSUE THREAD

**Issue by shuangzhijinghua** [txthinking/google-hosts#57]
谷歌亚太地区主要的IP段全部通过黑路由进行封锁(64.233.187.*/173.194.127.*/173.194.72.*/173.194.38.*/74.125.31.*/74.125.23.*/74.125.203.*/74.125.204.*/74.125.235.*/216.239.32.*)刚到骨干网就丢了，还没到国际出口。

**Comment by LGA1150** [comment]
除了gp外，其他googleusercontent都能用北京IP吗？
mail.google.com如果使用北京IP（证书一致），访问/mail/mu会403

**Comment by LGA1150** [comment]
supl.google.com应该是192结尾：
$ tcping 64.233.186.194 7272
64.233.186.194 port 7272 closed.
$ tcping 64.233.186.192 7272
64.233.186.192 port 7272 open.

**Comment by LGA1150** [comment]
talk.google.com和talk*.google.com应该是125结尾
mtalk.google.com才是188结尾（开放5228端口）

**Comment by shuangzhijinghua** [comment]
手机版mail会403，请求桌面版就没问题，appengine的验证也没事。
除了gp？，s？之外的googleusercontent.com都可以挂北京。

**Comment by LGA1150** [comment]
googleapis能否用北京IP

**Comment by shuangzhijinghua** [comment]
北京IP没有证书为googleapis.com的,也就没办法用了.
