### ISSUE TITLE
不能下载google code里的内容

### ISSUE THREAD

**Issue by wizholy** [txthinking/google-hosts#62]

**Comment by txthinking** [comment]
可以说下哪个域名吗

On Thu, Feb 12, 2015 at 1:22 PM, wizholy <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/62>.
>



-- 
About Me: http://www.txthinking.com

**Comment by wizholy** [comment]
google code页面都可以正常打开，但是具体到某个项目的下载页面无法下载。比如
https://cocos2d-iphone.googlecode.com/files/cocos2d-iphone-2.1.tar.gz
cocos2d的下载链接

**Comment by txthinking** [comment]
因为*.googlecode.com类似域名太多了，因为只要有人在googlecode上创建一个项目都会产生一个类似的域名，所以不可能全部加全的.
目前只加了几个常用的
last: 已经添加了cocos2d-iphone.googlecode.com

On Thu, Feb 12, 2015 at 4:00 PM, wizholy <notifications@github.com> wrote:

> google code页面都可以正常打开，但是具体到某个项目的下载页面无法下载。比如
> https://cocos2d-iphone.googlecode.com/files/cocos2d-iphone-2.1.tar.gz
> cocos2d的下载链接
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/62#issuecomment-74031607>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by wizholy** [comment]
这个脚本找IP应该很慢吧？
我需要europa-pso.googlecode.com的IP，能不能麻烦下，谢谢。
