### ISSUE TITLE
建议合并dnsmasq的配置文件

### ISSUE THREAD

**Issue by qwwujh** [txthinking/google-hosts#63]
建议合并dnsmasq的配置文件：
example:
address=/ggpht.com/261.58.217.1
所有的*.googleusercontent.com
*.googleapis.com
*.ggpht.com
*.books.google.com（可用国内ip203.208.46.177）
*.docs.google.com
*.drive.google.com
所有除了gmail，accounts，adwords的google二级域名都可直接合并为*.google.com
只要在*.google.com项的前面添加解析即可
例如
address=/accounts.google.com/203.208.46.177
address=/google.com/216.58.217.0
即可
另外,news.google.com,scholar.google.com,support.google.com,
earth.google.com,books.google.com,picasa.google.com,*.googlecode.com,
translate.googleusercontent.com,translate.google.com,accounts.google.com
play.google.com,chrome.google.com,code.google.com,*.l.google.com都可以挂在北京的服务器上，加速访问

**Comment by txthinking** [comment]
后续会更新 :D

**Comment by qwwujh** [comment]
国内ip已全部失效！！！！

**Comment by txthinking** [comment]
恩 一直以来此项目都没有采用国内IP

**Comment by joingithubcom** [comment]
同样希望合并精简dnsmasqconf。hosts一一对应，访问网址要求准确。dnsconf适应性强。尝试手工精简dnsmasqconf，费力不讨好，精简下来还有很多，因为有太多数字排列的ip地址，应该不需要那么多，精简下来有hodts十分之一那样才好，路由wget更新用来手机上网。

**Comment by txthinking** [comment]
好的 抽空我会合并下:D

**Comment by txthinking** [comment]
已合并
