### ISSUE TITLE
今天上Google是404啊

### ISSUE THREAD

**Issue by 312362115** [txthinking/google-hosts#64]
昨天还很正常的

**Comment by L34Rn** [comment]
404. That’s an error.

The requested URL /ncr was not found on this server. That’s all we know.

**Comment by L34Rn** [comment]
404

**Comment by 312362115** [comment]
最近两会的原因吧

**Comment by txthinking** [comment]
机器出现问题了 正在选择其他服务器提供商跑脚本

**Comment by 312362115** [comment]
脚本能改成多线程的么,跑的好慢

**Comment by joingithubcom** [comment]
刚更新的好像也不能用，才更新两小时就试了下

**Comment by txthinking** [comment]
刚买的服务器总宕机 换服务器ing

**Comment by xiaopangniuniu** [comment]
这几天还是一直404，大家也是这样么？还是我操作不正确？

**Comment by txthinking** [comment]
需要wait个几天

On Thu, Mar 5, 2015 at 4:24 PM, xiaopangniuniu <notifications@github.com>
wrote:

> 这几天还是一直404，大家也是这样么？还是我操作不正确？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/64#issuecomment-77324334>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by mogongzi** [comment]
TX辛苦啦！

**Comment by txthinking** [comment]
是应该改成多线程的，惭愧一直比较忙，希望能尽快整理下自己的时间吧

On Thu, Mar 5, 2015 at 8:18 PM, Ryan Ren <notifications@github.com> wrote:

> TX辛苦啦！
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/64#issuecomment-77354449>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by joingithubcom** [comment]
请问为什么不同时更新.conf，我路由wget的是conf文件。不精简不使用泛解析直接转换几秒钟的事。

**Comment by txthinking** [comment]
好的, 我会尽快更新的conf的

On Fri, Mar 6, 2015 at 6:13 PM, joingithubcom <notifications@github.com>
wrote:

> 请问为什么不同时更新.conf，我路由wget的是conf文件。不精简不使用泛解析直接转换几秒钟的事。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/64#issuecomment-77536011>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by txthinking** [comment]
updated hosts

**Comment by txthinking** [comment]
#29
