### ISSUE TITLE
youtube无法登陆了。

### ISSUE THREAD

**Issue by gitawego** [txthinking/google-hosts#65]
刚更新了HOST，谷歌又可以上了，但是youtube上不了了。。提示信息：

    youtube.com 通常使用加密技术来保护您的信息。Chrome 此次尝试连接到 youtube.com 时，此网站返回了异常的错误凭据。
    这可能是因为有攻击程序在试图冒充 youtube.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chrome 尚未进行任何数据交换便停止了连接。

    您目前无法访问youtube.com，因为此网站使用了HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by joingithubcom** [comment]
好似是长城搞的鬼，上网还得注意证书

**Comment by txthinking** [comment]
机器出现问题了 正在选择其他服务器提供商跑脚本

**Comment by txthinking** [comment]
#29
