### ISSUE TITLE
能增加对dropbox的支持吗？

### ISSUE THREAD

**Issue by zhanh1218** [txthinking/google-hosts#66]

**Comment by txthinking** [comment]
目前仅提供google的访问

**Comment by cantonadong** [comment]
考虑对其他网站支持吗？flickr之类的。

**Comment by txthinking** [comment]
暂时只维护google的吧. dropbox的话估计将自己的dns换成opendns能改善下.

On Sun, Mar 15, 2015 at 4:09 PM, Cantona Dong <notifications@github.com>
wrote:

> 考虑对其他网站支持吗？flickr之类的。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/66#issuecomment-80908270>
> .
>



-- 
About Me: http://www.txthinking.com

**Comment by wonleing** [comment]
给个hosts的更新链接吧 Google又访问不了了

发自我的 iPhone

**Comment by txthinking** [comment]
Readme 有链接啊
