### ISSUE TITLE
fonts.googleapis.com已经解禁

### ISSUE THREAD

**Issue by aesean** [txthinking/google-hosts#68]
fonts.googleapis.com已经解禁，现在fonts.googleapis.com会被解析到203.208.48.*，使用美帝的地址延迟会非常高。

**Comment by txthinking** [comment]
目前不建议使用国内IP, 如果需要可自行修改部分hosts

**Comment by aesean** [comment]
好吧，googleapis.com是最近刚解禁的，现在被墙解析到北京Google的服务器，我本地使用Hosts里Google美帝的地址会非常卡，丢包也很多，用国内的速度会非常好。
