### ISSUE TITLE
建议使用Fing工具来对ip段443端口进行筛选

### ISSUE THREAD

**Issue by qwwujh** [txthinking/google-hosts#70]
建议从bgp.he.net中找到google inc的ip段，然后在android/iphone手机上用Fing( Fing Network Tools)工具来对ip段443端口进行筛选（建议使用流量扫描,扫完整个173.194.0.0/16大约要45min，一次10几M），然后根据主机名称中的dns编码来进行选择.

**Comment by txthinking** [comment]
#48
