### ISSUE TITLE
计划去掉公开自动更新, 改成邮件自动获取实时.

### ISSUE THREAD

**Issue by txthinking** [txthinking/google-hosts#73]
当然更希望有条件的同学自己使用脚本

**Comment by 312362115** [comment]
why

**Comment by joingithubcom** [comment]
那么路由wget自动获取行不通了，还有什么好方案吗，希望保留dnsmasq.conf公开。况且是小众使用，且不能逆向转成hosts应该不会被盯上吧。

**Comment by txthinking** [comment]
觉得封的有点快 大家觉得如何 最近抽风严重不 采取大家意见

**Comment by wizholy** [comment]
最近疯的很快，如何邮件自动获取

**Comment by txthinking** [comment]
就是类似发送一封邮件 过会变自动收到一个最新hosts文件 不过还没开发

**Comment by senRsl** [comment]
出了正月，土匪又开始上班了，所以最近封的快

**Comment by jarryzhang** [comment]
Hi,

I want to get the new hosts. thanks!



Best Regards,
Jun Zhang
 
发件人： senRsl DC
发送时间： 2015-03-26 17:24
收件人： txthinking/google-hosts
主题： Re: [google-hosts] 计划去掉公开自动更新, 改成邮件自动获取实时. (#73)
出了正月，土匪又开始上班了，所以最近封的快

**Comment by qwwujh** [comment]
216.58.221.111 Google最后一个香港服务器

**Comment by qwwujh** [comment]
如果gfw的员工订阅了邮件呢？

**Comment by qwwujh** [comment]
建议每封邮件内的IP都不同

**Comment by txthinking** [comment]
优化了每日更新规则

**Comment by txthinking** [comment]
更新了镜像

**Comment by txthinking** [comment]
建议大家平时使用境外dns, google dns,opendns等等，当然又快别人又不知道的境外DNS最好了

**Comment by txthinking** [comment]
不去掉了

**Comment by txthinking** [comment]
另外我会升级下自己的VPS的cpu和带宽, 进程就能一次能跑多点，希望更新再快点

**Comment by senRsl** [comment]
建议http://freedom.txthinking.com/hosts不要使用固定链接，用户必须访问页面点几个按钮之后才显示hosts内容，可以有效防止gfw抓取。
