### ISSUE TITLE
停止自动更新hosts, 希望大家自己看README使用脚本生成hosts自用

### ISSUE THREAD

**Issue by txthinking** [txthinking/google-hosts#77]
因为死的太快.

如果自动查出的某个IP不能用, 使用filter手动测试出可用的即可. 这个看下README就知道了.

**最好不要大范围传播**

**Comment by kwx** [comment]
你好 txthinking，请问一下 
./iprange_x86_64: cannot execute binary file
错误是怎么回事呢？

**Comment by txthinking** [comment]
是linux系统吗

**Comment by kwx** [comment]
是苹果的 OSX 10.10.2

**Comment by txthinking** [comment]
https://github.com/txthinking/google-hosts/blob/master/scripts/README.md

**Comment by cantonadong** [comment]
怎么用啊，更新后都用不了了。

**Comment by txthinking** [comment]
@cantonadong 
因为公开传播封的太快，
我每天都会去跑一遍（如果自动跑出来的不能用，我还要手动filter挑选), (之前小传播范围时一个月不用更新还能用)
而且我买的还算不错的国内某VPS还经常抽风, 配置不太高, 带宽也是小水管, 所以有时会导致工作有点卡(因为俺工作是ssh到俺的VPS敲代码, 不在本机弄工作环境)
授人与鱼不如授人与渔. 所以希望大家能学会使用渔具, 基本上自己跑出来的结果自用的话应该存活期还可以. 当然偶尔俺也会更新.( 之前公开的freedom.xxxx.xxx的相关链接应该还能用 :santa: )
脚本为什么不支持OSX的: 因为osx上面的grep, awk等工具 和 linux 上的`GUN grep`,` GUN awk `有很大区别. 俺开发用的是Linux. (在万恶的osx上装个vagrant上linux吧 :D)

**Comment by cantonadong** [comment]
@txthinking 抱歉，你那个readme我完全看不懂…
怎么跑？怎么filter？用什么工具？在win上可以跑吗？

**Comment by XhstormR** [comment]
我也是不懂在windows平台下怎么运行这些脚本...

**Comment by yy1300326388** [comment]
我建议去用GO Go Tester这款软件：
地址：[http://blog.csdn.net/yy1300326388/article/details/44962429](http://blog.csdn.net/yy1300326388/article/details/44962429)

**Comment by txthinking** [comment]
脚本只能在Linux运行
