### ISSUE TITLE
google-hosts 出来的ip会重定向到http://www.google.com/hangouts/

### ISSUE THREAD

**Issue by FunnyMore** [txthinking/google-hosts#79]
感觉这是谷歌在使坏，简直有点丧心病狂，不拿墙内用户当用户，这样访问似乎没问题：
https://www.google.com/?gws_rd=ssl

**Comment by txthinking** [comment]
有时跑出来的IP会有这种情况, 尽管证书是*.google.com, 但是Google使此IP仅服务于hangouts
解决方案:
0. `$ cd scripts/`
1. `$ ./filter.sh *.google.com | less` 手动过滤 *.google.com的IP
2. 过滤出的 IP, 从上面往下挨个手动测试写入本地hosts ` x.x.x.x www.google.com`, 直到不被重定向到hangouts便为可用IP.
3. 手动修改下跑出来hosts文件, 用过滤出的这个IP批量替换下那个让你重定向的错误IP

**Comment by LGA1150** [comment]
@txthinking 
hangouts的IP有个特点，就是会开放5222端口
你可以通过检测5222端口是否开放来判断是否为hangouts的IP

**Comment by txthinking** [comment]
@LGA1150 Thank you
