### ISSUE TITLE
执行find.sh出错

### ISSUE THREAD

**Issue by inaveu** [txthinking/google-hosts#80]
$ uname -m
i686
所以执行find.sh时出现找不到iprange_i686，怎么办？谢谢

**Comment by txthinking** [comment]
试试:
```
$ cd scripts
$ cp iprange_i386 iprange_i686
```
然后再find

**Comment by txthinking** [comment]
@inaveu 可以了吗

**Comment by justin-tang** [comment]
find.sh
出现以下问题请问怎么解决：
./find.sh: line 23: ./iprange_x86_64: cannot execute binary file
./find.sh: line 24: ./iprange_x86_64: cannot execute binary file
./find.sh: line 39: ((: i=: syntax error: operand expected (error token is "=")

**Comment by txthinking** [comment]
@justinTang 是Linux系统吗?
https://github.com/txthinking/google-hosts/blob/master/scripts/README.md
