### ISSUE TITLE
Help, why 'no output directory' ?

### ISSUE THREAD

**Issue by xujchen** [txthinking/google-hosts#83]
Why the results are `no output directory`?

I went to the folder `google-hosts-master/scripts/`, and then:
`$./filter.sh mail.google.com`
`no output directory.`
`$./select.sh`
`no output directory.`

**Comment by txthinking** [comment]
You must run ./auto.sh first, this script will create output directory.
$ ./auto.sh

BTW, Don't forget to check Requirements:
https://github.com/txthinking/google-hosts/blob/master/scripts/README.md
