### ISSUE TITLE
it looks like google.com no longer valid

### ISSUE THREAD

**Issue by walkthetalk** [txthinking/google-hosts#84]
always connecting...

**Comment by rexdf** [comment]
据我观察，好像是谷歌自己屏蔽了很多IP，有些网段证书好像都取消了，有些比较快的IP改成了返回301

**Comment by walkthetalk** [comment]
怎么办？

**Comment by txthinking** [comment]
是那个IP有问题了吗

**Comment by rexdf** [comment]
需要观察看看,我把那些好的*.google.com的确认没有被墙的ip手动试了很多，都是排在前面的，几乎全部都是301。暂时办法是用单独的www.google.com的ip，结果是302.这样就可以用了

**Comment by txthinking** [comment]
301跳转地址是什么

**Comment by rexdf** [comment]
<HTML><HEAD><TITLE>301 Moved Permanently</TITLE></HEAD><BODY><H1>302 Moved</H1>T
he document has moved permanently<A HREF="http://www.google.com/hangouts/">here<
/A>.</BODY></HTML>

难道是我的IP选错了？

**Comment by txthinking** [comment]
更新下项目 git pull fixed at #79
