### ISSUE TITLE
第一次用，为什么好像一个ip都找不到？

### ISSUE THREAD

**Issue by bonedriven** [txthinking/google-hosts#87]
先是./auto.sh了一下，满屏的No No No

后来手动试，到select.sh发现hosts.all根本没有更新，只有warning？
[WARNING] *.google.com
[WARNING] accounts.google.com
[WARNING] checkout.google.com
[WARNING] adwords.google.com
[WARNING] mail.google.com
[WARNING] *.mail.google.com
[WARNING] *.googleusercontent.com
[WARNING] *.gstatic.com
[WARNING] *.googleapis.com
[WARNING] *.appspot.com
[WARNING] *.googlecode.com
[WARNING] *.google-analytics.com
[WARNING] ssl.google-analytics.com

**Comment by txthinking** [comment]
先检查下依赖:
https://github.com/txthinking/google-hosts/blob/master/scripts/README.md

**Comment by bonedriven** [comment]
感谢，是我的错，没有注意依赖。。

有个问题，

我是手动执行的

#!/usr/bin/env bash
# 
# 寻找IP并自动更新
#
# Author: cloud@txthinking.com
#

for i in $(nslookup -q=TXT _netblocks.google.com 8.8.4.4 | grep -Po '\d+\.\d+\.\d+.\d+\/\d+')
do
    ./find.sh $i
done

之后执行了select.sh,因为我想先看看找到的hosts是什么样的，所以没有直接执行auto.sh
结果是命令好显示我找到10个左右的谷歌服务ip外，有两个warning
[WARNING] *.google.com
[WARNING] ssl.google-analytics.com
没有找到youtube或者说谷歌音乐的，这个正常吗？如果需要谷歌音乐或者youtube的应该是怎么找的？
还是说执行auto.sh就可以找全呢？

**Comment by txthinking** [comment]
```
for i in $(nslookup -q=TXT _netblocks.google.com 8.8.4.4 | grep -Po '\d+\.\d+\.\d+.\d+\/\d+')
do
    ./find.sh $i
done
```
这段应该会跑一会吧

**Comment by txthinking** [comment]
会生成output目录看看里面的文件

或者

`./filter.sh *.google.com` 过滤下

**Comment by bonedriven** [comment]
是我的问题，应该是那个还没算完我就运行了select.sh,导致得到的结果不全。重新正在算，挺耗时的（我用的一个配置比较低的vps在找）。谢谢答复。

另外请问下，每算一次得到的ip一般有效性有多长？

**Comment by txthinking** [comment]
几个小时吧, 如果你熟悉代码和unix调优的话，你可以调整代码里的最大进程数得到最快的运行速度

**Comment by bonedriven** [comment]
几个小时的寿命，实在是太短。。。。之前以为能至少有一周。。那样我还在想是否弄个每周自动计算更新一次hosts的小script。。。
基本不懂代码。。。

**Comment by txthinking** [comment]
错了，我以为你说的是跑完脚本要多长时间呢，不好意思。
寿命的话，这个不一定，有时几周，有时几天。有时几个月。

**Comment by bonedriven** [comment]
哦，那太好了。
我昨天在亚马逊给的免费一年的vps上算了一套ip，然后更新在墙内电脑的hosts上，发现google+，邮箱，music什么的没一个能上去。
不知道是不是必须要在墙内的电脑算才行？

**Comment by txthinking** [comment]
肯定要用国内的vps啊  = =||

**Comment by bonedriven** [comment]
嗯嗯，不好意思，傻了。。
