### ISSUE TITLE
为什么都不能用了

### ISSUE THREAD

**Issue by gushoubang** [txthinking/google-hosts#89]
最近好长一段时间都不能用了

**Comment by txthinking** [comment]
封完了呗 (?)

On Tue, Aug 25, 2015 at 9:29 AM, XiaoGu <notifications@github.com> wrote:

> 最近好长一段时间都不能用了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/txthinking/google-hosts/issues/89>.
>



-- 
About Me: http://www.txthinking.com

**Comment by royJang** [comment]
https://github.com/royJang/iSystem 可以一键更新hosts,一键添加知名开源hosts,可以试试
