### ISSUE TITLE
Repo tagged with incorrect language

### ISSUE THREAD

**Issue by wbuchanan** [txthinking/google-hosts#91]
Your repository is being tagged as Stata even though there isn't any Stata code available in it.

**Comment by txthinking** [comment]
You are right, this look like a detecting bug of github

**Comment by wbuchanan** [comment]
Supposedly there is a way that the repo owner can correct things, but it isn't completely clear how to do so.  I filed an issue with github/linguist since it happened a few other times with forks/related projects to this one here [https://github.com/github/linguist/issues/2747](https://github.com/github/linguist/issues/2747).

**Comment by arfon** [comment]
You can ask GitHub to ignore this file using the [Linguist overrides](https://github.com/github/linguist#overrides). For this repository you'd need a `.gitattributes` file with the following:

```
scripts/*.do linguist-vendored=true
```
