### ISSUE TITLE
can't run with auto.sh

### ISSUE THREAD

**Issue by fhbzyc** [txthinking/google-hosts#94]
MacBook-Air:~ joshua$ cd google-hosts/scripts && ./auto.sh
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
**no output directory.**

How do I?

**Comment by txthinking** [comment]
https://github.com/txthinking/google-hosts/blob/master/scripts/README.md

**Comment by armysheng** [comment]
依赖都没有问题,同样报错

**Comment by txthinking** [comment]
`同样报错` 是指错误信息和上面一样吗

**Comment by armysheng** [comment]
只报了 **no output directory.**

**Comment by txthinking** [comment]
请提供更详细的步骤
$ step 1
...output...
$ step 2
...output...
$ step 3
...output...

**Comment by armysheng** [comment]
只echo了一句这个话**no output directory.**,我已经找了份hosts手动改了, thanks any way.

**Comment by txthinking** [comment]
我只能猜测你的情况可能是
https://github.com/txthinking/google-hosts/blob/master/scripts/auto.sh#L8
这一行的8.8.4.4在你的网络下是不通的，可尝试将auto.sh里的8.8.4.4替换为其他你可以连接的境外某DNS.
